# Generated by Django 2.2.6 on 2019-10-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=100)),
                ('hcpcs_code', models.CharField(blank=True, max_length=5, null=True)),
                ('route_type', models.CharField(blank=True, max_length=10, null=True)),
                ('cpt_dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('numerator_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpt_mbu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mbus_per_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mbus_per_ndc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_of_service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='os_contracts.Manufacturer', to_field='name')),
            ],
            options={
                'unique_together': {('ndc_code', 'hcpcs_code')},
            },
        ),
    ]
