# Generated by Django 2.2.6 on 2019-10-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='drug',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='drug',
            name='cpt_mbu',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='hcpcs_code',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='mbus_per_ndc',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='mbus_per_package',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='ndc_code',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='numerator_strength',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='package_qty',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='units_of_service',
        ),
        migrations.CreateModel(
            name='NDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(max_length=13)),
                ('hcpcs_code', models.CharField(blank=True, max_length=5, null=True)),
                ('numerator_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpt_mbu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mbus_per_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mbus_per_ndc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_of_service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndcs', to='os_contracts.Drug', to_field='name')),
            ],
            options={
                'unique_together': {('ndc_code', 'hcpcs_code')},
            },
        ),
    ]
