# Generated by Django 2.2.6 on 2019-10-23 14:03

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('os_contracts', '0002_auto_20191021_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndc',
            options={'verbose_name': 'NDC', 'verbose_name_plural': 'NDCs'},
        ),
        migrations.AddField(
            model_name='drug',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2019, 10, 23, 14, 3, 5, 466807, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
