# Generated by Django 2.2.6 on 2019-10-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_account_id', models.CharField(blank=True, max_length=6, null=True)),
                ('os_account', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ndc_code', models.CharField(blank=True, max_length=13, null=True)),
                ('hcpcs_code', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('item_description', models.CharField(blank=True, max_length=100, null=True)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('backordered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('awp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('billing_unit', models.IntegerField(blank=True, max_length=10, null=True)),
                ('billing_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('billing_units_per_package', models.CharField(blank=True, max_length=100, null=True)),
                ('asp_per_billing_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('is_credit', models.BooleanField()),
                ('route_of_administration_code_description', models.CharField(blank=True, max_length=100, null=True)),
                ('mbus_per_ndc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('units_of_service', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('extended_ordered_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('extended_delivered_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
