# Generated by Django 2.2.6 on 2019-10-30 19:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('route_type', models.CharField(blank=True, max_length=10, null=True)),
                ('cpt_dosage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='NDC',
            fields=[
                ('ndc_code', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('hcpcs_code', models.CharField(blank=True, max_length=5, null=True)),
                ('numerator_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpt_mbu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mbus_per_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mbus_per_ndc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ndc_unit_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drug_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndcs', to='os_contracts.Drug')),
            ],
            options={
                'verbose_name': 'NDC',
                'verbose_name_plural': 'NDCs',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='os_contracts.Manufacturer'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_category', models.CharField(blank=True, max_length=10, null=True)),
                ('measured_equivalents_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('measured_equivalents_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('G', 'Growth'), ('V', 'Volume'), ('MS', 'Market Share'), ('P', 'Portfolio'), ('VG', 'Volume/Growth'), ('GMS', 'Growth/Market Share'), ('GP', 'Growth/Portfolio'), ('VMS', 'Volume/Market Share'), ('VMS', 'Volume/Market Share')], max_length=50, null=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('baseline_start_date', models.DateField(blank=True, null=True)),
                ('baseline_end_date', models.DateField(blank=True, null=True)),
                ('baseline_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('rebate_schedule', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('drug_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='os_contracts.Drug')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='os_contracts.Manufacturer')),
            ],
        ),
    ]
