# Generated by Django 2.2.5 on 2019-11-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_auto_20191101_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'get_latest_by': ['invoice_date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
