# Generated by Django 2.2.6 on 2019-11-02 21:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_auto_20191101_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount_schedule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='measurement_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='measurement_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
