# Generated by Django 2.2.6 on 2019-11-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_auto_20191102_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['drug_name']},
        ),
    ]
